export const REQUEST_AGENDA = 'REQUEST_AGENDA';
export const RECEIVE_AGENDA = 'RECEIVE_AGENDA';
export const AGENDA_REQUEST_ERROR = 'AGENDA_REQUEST_ERROR';
export const REQUEST_SPEAKERS = 'REQUEST_SPEAKERS';
export const RECEIVE_SPEAKERS = 'RECEIVE_SPEAKERS';
export const AGENDA_ERROR = 'RECEIVE_AGENDA_ERROR';
export const TOGGLE_FAVOURITE = 'TOGGLE_FAVOURITE';
