export const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS';
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const QUESTIONS_REQUEST_ERROR = 'QUESTIONS_REQUEST_ERROR';
export const QUESTIONS_ERROR = 'RECEIVE_QUESTIONS_ERROR';
export const TOGGLE_FAVOURITE = 'TOGGLE_FAVOURITE';
